[package]
name = "nodio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
eframe = "0.27.2"
egui = "0.27.2"
egui_nodes = { git = "https://github.com/tinted-software/egui_nodes.git" }
